language: php

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - cd vendor/phpexiftool/phpexiftool/lib/vendor/Exiftool && git submodule update --init

php:
  - 5.3
  - 5.4
